version: '3'

services:
	selenium-hub:
	image: selenium/hub
	ports:
	- "4442-4444:4442-4444"
	network:
	- grid
	
	node-chrome:
	image: selenium/node-chrome
	enviroment:
	- SE_EVENT_BUS_HOST=selenium-hub
	- SE_EVENT_BUS_PUBLISH+PORT=4442
	- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
	networks
	- grid
	
	node-firefox:
	image: selenium/node-firefox
	enviroment:
	- SE_EVENT_BUS_HOST=selenium-hub
	- SE_EVENT_BUS_PUBLISH+PORT=4442
	- SE_EVENT_BUS_SUBSCRIBE_PORT=4443
	networks
	- grid

networs:
   grid:
driver:bridge	   
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	
	